language: cpp
sudo: required
dist: trusty
env:
  matrix:
  - DISTRO=ubuntu-16.04
  - DISTRO=ubuntu-17.04
  - DISTRO=ubuntu-17.10
  - DISTRO=opensuse-42.3
services:
- docker
before_install:
- docker build config/docker/${DISTRO} -t dev/zookeeper-cpp/${DISTRO}
script:
- echo ${COVERALLS_REPO_TOKEN} > ${TRAVIS_BUILD_DIR}/coveralls-repo-token
- docker run -v ${TRAVIS_BUILD_DIR}:/root/zookeeper-cpp dev/zookeeper-cpp/${DISTRO}
